repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.10
    hooks:
      - id: ruff-check
        args: [--fix, --config=pyproject.toml]

      - id: ruff-format

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.404
    hooks:
      - id: pyright
        language: system